### ISSUE TITLE
Layout of iOS tab has overlap on iOS 8.X sim

### ISSUE THREAD

**Issue by ewieberappc** [appcelerator-developer-relations/appc-sample-ti510#3]
The date picker overlaps the text just after it on the iOS tab when using an iOS 8.3 sim

**Steps to reproduce issue**
1. Launch the app
2. Go to the iOS tab

**Actual Results**
The picker overlaps the text after it

**Expected Results**
The picker does not overlap the text

![screen shot 2015-11-20 at 11 01 17 am](https://cloud.githubusercontent.com/assets/6341646/11308987/0fd36e44-8f76-11e5-82fe-24a8def43d9d.png)

Tested using:
MacOS 10.11.2 (15C40a)
Studio 4.4.0.201511130407
Ti SDK 5.1.0.v20151118214427
Appc NPM 4.2.2-1
Appc CLI 5.1.0-60
Ti CLI 5.0.5
Alloy 1.7.26
Arrow 1.3.22
Xcode 7.1 (7B91b)
Node v0.12.7
Java 1.7.0_80

**Comment by FokkeZB** [comment]
The app is iPhone only as you can see in the tiapp.xml

I wonder why the height of the picker is not the 50 it is set to. Perhaps that only works on ios9. Will check that but don't think it's a blocker

**Comment by ewieberappc** [comment]
Ah, then we may have a different issue where I am still able to deploy to 'unchecked' targets. Updating ticket to be an iPhone sim.

**Comment by FokkeZB** [comment]
You've found a bug
https://jira.appcelerator.org/browse/TIMOB-20028
