### ISSUE TITLE
Text for setting "Slow Animation" is incorrect for sims

### ISSUE THREAD

**Issue by ewieberappc** [appcelerator-developer-relations/appc-sample-ti510#4]
The text in the Auto Layout tab says that (⌘L) will set Slow Animation, however this is the command to lock the sim and is stated as such in the iOS tab.

**Steps to reproduce issue**
1. Launch the app
2. Go to the Auto Layout tab

**Actual Results**
The text claims that (⌘L) will set Slow Animation, when it really locks the device, as stated in the iOS tab

**Expected Results**
The appropriate commands/steps are listed in the text

![screen shot 2015-11-20 at 10 18 04 am](https://cloud.githubusercontent.com/assets/6341646/11308255/f2effcce-8f71-11e5-81e1-6c2976e16291.png)

Tested using:
MacOS 10.11.2 (15C40a)
Studio 4.4.0.201511130407
Ti SDK 5.1.0.v20151118214427
Appc NPM 4.2.2-1
Appc CLI 5.1.0-60
Ti CLI 5.0.5
Alloy 1.7.26
Arrow 1.3.22
Xcode 7.1 (7B91b)
Node v0.12.7
Java 1.7.0_80

**Comment by FokkeZB** [comment]
Should be T - will correct

**Comment by grantges** [comment]
that was part of my pull request FYI
