### ISSUE TITLE
Notifications permission not set on iOS 8.x sims. Should state TEXTINPUT is not supported

### ISSUE THREAD

**Issue by ewieberappc** [appcelerator-developer-relations/appc-sample-ti510#5]
On iOS 8.X simulators the alerts permission is not set so the TEXTINPUT feature in the iOS tab does not work (does not display the alert to interact with). Since the text input feature is not supported in iOS 8, this should be noted in the text above the button or should not be present when running on a device that does not support it.

**Steps to reproduce issue**
1. Open the app on an iOS 8.X sim/device
2. Allow Notifications, if asked
3. Go to the iOS Tab
4. Scroll down and click the TEXTINPUT button
5. Press the home button

**Actual Results**
No alert appears

**Expected Results**
The text above the butoon explains that this feature is not available on iOS 8.x or the button does not display on iOS 8.x

**Notes**
You get the below message when the notification is scheduled. It states that permissions have not been set.

    [INFO] :   2015-11-20 10:21:04.937 Ti 5.1.0[51261:11530092] Attempting to schedule a local notification <UIConcreteLocalNotification: 0x79f813a0>{fire date = Friday, November 20, 2015 at 10:21:09 AM Pacific Standard Time, time zone = America/Los_Angeles (PST) offset -28800, repeat interval = 0, repeat count = UILocalNotificationInfiniteRepeatCount, next fire date = Friday, November 20, 2015 at 10:21:09 AM Pacific Standard Time, user info = (null)} with an alert but haven't received permission from the user to display alerts

**Comment by hansemannn** [comment]
Should something like this here:
```javascript
function notification() {

	Ti.App.iOS.registerUserNotificationSettings({
		types: [
		    Ti.App.iOS.USER_NOTIFICATION_TYPE_ALERT,
		    Ti.App.iOS.USER_NOTIFICATION_TYPE_SOUND,
		    Ti.App.iOS.USER_NOTIFICATION_TYPE_BADGE
		]
	});

	function registerForPush() {
		Ti.Network.registerForPushNotifications({
			success : function() {
				Ti.App.iOS.scheduleLocalNotification({
					alertBody: 'Select the \'Input\' action.',

					// Notify in 5 seconds
					date: new Date(new Date().getTime() + 5000),

					// Select the sample category registered in registerUserNotificationSettings()
					category: 'sample'
				});

				alert('Now lock the phone or press Home to see the notification in 5s.');
			},
			error : function() {
				alert("You did not grant the permissions!");
			},
			callback : function() {
				alert("Callback received!");
			}
		});
		// Remove event listener once registered for push notifications
		Ti.App.iOS.removeEventListener('usernotificationsettings', registerForPush);
	};

	// Wait for user settings to be registered before registering for push notifications
	Ti.App.iOS.addEventListener('usernotificationsettings', registerForPush);
}

```

**Comment by FokkeZB** [comment]
Yep, will get that in tomorrow

**Comment by FokkeZB** [comment]
OK, we have a bug here. I've changed the minimum iOS version to 9.1 now but this is what happening:

* I've now completely followed http://docs.appcelerator.com/platform/latest/#!/guide/iOS_Local_Notifications even though listening to `usernotificationsettings` is only needed if you want to send push notifications AFAIK.
* On iOS 8.4 it indeed does not prompt for permissions, but it **does** fire the `usernotificationsettings` event but the `types` properties is an empty array.
* If you don't move the app to the background it **does** fire the `notification` event I've now added a listener for.

So this seems to be a bug in Titanium :(

**Comment by FokkeZB** [comment]
The following works fine on both iOS 8.4 and 9.1 with Ti 5.0.2 and 5.1.0. Weird :(

```
Ti.App.iOS.registerUserNotificationSettings({
	types: [
		Ti.App.iOS.USER_NOTIFICATION_TYPE_ALERT,
		Ti.App.iOS.USER_NOTIFICATION_TYPE_SOUND,
		Ti.App.iOS.USER_NOTIFICATION_TYPE_BADGE
	]
});

Ti.App.iOS.addEventListener('usernotificationsettings', function(e) {
	console.log('Ti.App.iOS:usernotificationsettings ' + JSON.stringify(e, null, 2));
});

Ti.App.iOS.addEventListener('notification', function(e) {
	console.log('Ti.App.iOS:notification ' + JSON.stringify(e, null, 2));
});

var win = Ti.UI.createWindow({
	backgroundColor: 'white'
});

win.addEventListener('click', function() {
	console.log('Scheduled notification...');

	var notification = Ti.App.iOS.scheduleLocalNotification({
		alertBody: 'It did work',
		date: new Date(Date.now() + 3000)
	});
});

win.open();
```

**Comment by FokkeZB** [comment]
But somehow in the Ti 5.1.0 sample app, even if I put the above code in `alloy.js` it says:

```
[INFO]  Ti.App.iOS:usernotificationsettings {
[INFO]    "types": [],
[INFO]    "categories": [],
[INFO]    "bubbles": true,
[INFO]    "type": "usernotificationsettings",
[INFO]    "source": {},
[INFO]    "cancelBubble": false
[INFO]  }
[INFO]  2015-11-23 11:06:26.930 Ti 5.1.0[89309:6197125] Attempting to schedule a local notification <UIConcreteLocalNotification: 0x7f9668596d80>{fire date = Monday, November 23, 2015 at 11:06:31 AM Central European Standard Time, time zone = Europe/Amsterdam (GMT+1) offset 3600, repeat interval = 0, repeat count = UILocalNotificationInfiniteRepeatCount, next fire date = Monday, November 23, 2015 at 11:06:31 AM Central European Standard Time, user info = (null)} with an alert but haven't received permission from the user to display alerts
[TRACE] [Ti 5.1.0] Attempting to schedule a local notification <UIConcreteLocalNotification: 0x7f9668596d80>{fire date = Monday, November 23, 2015 at 11:06:31 AM Central European Standard Time, time zone = Europe/Amsterdam (GMT+1) offset 3600, repeat interval = 0, repeat count = UILocalNotificationInfiniteRepeatCount, next fire date = Monday, November 23, 2015 at 11:06:31 AM Central European Standard Time, user info = (null)} with an alert but haven't received permission from the user to display alerts
```

Any idea @hansemannn ?

**Comment by FokkeZB** [comment]
OMG....

https://github.com/appcelerator-developer-relations/appc-sample-ti510/blob/master/app/controllers/ios.js#L185

`type !== types`

Strange that it works on iOS 9.1 though ;)
